spring:
  config:
    import: optional:classpath:application-local.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/newport-whale
    username: ${DB_USER:}
    password: ${DB_PASS:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration