spring:
  config:
    import: optional:classpath:application-local.yml
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/newport-whale}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASS:}}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.mansurtiyes: DEBUG   # your app’s package

# <-- add this block at root level
server:
  port: ${PORT:8080}